spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://root:123456x@47.106.232.11:27017,47.106.232.11:27018,47.106.232.11:27019/mpn?replicaSet=BigBoss
      authentication-database: admin